name: Run Bot

on:
  workflow_dispatch:

jobs:
  start-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        env:
          OWNER_NUMBER: ${{ secrets.OWNER_NUMBER }}
          OWNER_NAME: ${{ secrets.OWNER_NAME }}
          BOT_NAME: ${{ secrets.BOT_NAME }}
          BOT_IMAGE: ${{ secrets.BOT_IMAGE }}
        run: node index.js
